# Generated by Django 5.1.4 on 2024-12-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reCAPTCHA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reCAPTCHA',
        ),
    ]
